n = 14
(
    GET_LANG,
    GET_NAME,
    GET_CONTACT,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    GET_VISIT_TYPE,
    GET_VISIT_ADRESS,
    GET_VISIT_COMMENT,
    GET_VISIT_LOCATION,
    CONFIRM_VISIT,
    GET_VIDEO_NOTE,


) = range(0, n)